/**
 * Required attributions when `authorAttributions` is non-empty (Places API policy).
 * Generated by: npm run fetch:venue-google-photos
 */
export type GooglePhotoAttribution = { displayName: string; uri?: string };

export const VENUE_GOOGLE_ATTRIBUTIONS: Partial<
  Record<string, GooglePhotoAttribution[]>
> = {};
