/**
 * Local first-party hero images for directory places.
 * Auto-generated by scripts/fetch-venue-images.ts — do not edit by hand.
 * Re-run: npm run fetch:venue-images
 */
export const VENUE_LOCAL_IMAGE_BY_SLUG: Partial<Record<string, string>> = {
  'aticco-glories': '/images/venues/aticco-glories.webp',
  'blueproject-foundation': '/images/venues/blueproject-foundation.jpg',
  'el-molino': '/images/venues/el-molino.png',
  'escat-gallery': '/images/venues/escat-gallery.jpg',
  'espronceda-institute': '/images/venues/espronceda-institute.jpg',
  'ethall': '/images/venues/ethall.jpg',
  'fab-lab-barcelona': '/images/venues/fab-lab-barcelona.jpg',
  'faire-barcelona': '/images/venues/faire-barcelona.png',
  'frizzant': '/images/venues/frizzant.jpg',
  'heliogabal': '/images/venues/heliogabal.jpg',
  'house-of-chappaz': '/images/venues/house-of-chappaz.jpg',
  'la-papa-coffee': '/images/venues/la-papa-coffee.png',
  'les-enfants-brillants': '/images/venues/les-enfants-brillants.jpg',
  'moonlight-studio': '/images/venues/moonlight-studio.jpg',
  'nogueras-blanchard': '/images/venues/nogueras-blanchard.jpg',
  'ona-restaurant': '/images/venues/ona-restaurant.jpg',
  'syra-coffee': '/images/venues/syra-coffee.jpg',
  'transfolab-bcn': '/images/venues/transfolab-bcn.jpg',
  'zen-kannon': '/images/venues/zen-kannon.jpg',
};
