import type { HikingRoute } from './types';

/**
 * Curated Catalunya routes for enthusiasts — editorial picks, not live OSM import.
 * Metrics are typical values; always verify closures and weather via official sources.
 */
export const CATALUNYA_HIKES: HikingRoute[] = [
  {
    id: 'hike-collserola-tibidabo',
    slug: 'collserola-tibidabo-loop',
    name: 'Collserola — Tibidabo & les Planes loop',
    summary:
      'Shaded forest tracks and wide views over Barcelona — an accessible training ground with many variants.',
    region: 'barcelona-metro',
    comarca: 'Barcelonès',
    difficulty: 'easy',
    distanceKm: 12,
    elevationGainM: 380,
    durationHours: 3.5,
    center: { lat: 41.421, lon: 2.119 },
    tags: ['forest', 'city-escape', 'loop'],
    infoUrl: 'https://www.barcelona.cat/es/whatson/agenda/p/parc-de-collserola',
  },
  {
    id: 'hike-montserrat-sant-jeroni',
    slug: 'montserrat-sant-jeroni',
    name: 'Montserrat — Sant Jeroni from Monistrol',
    summary:
      'The classic needle landscape: hermitages, stairs, and the highest summit in the massif with huge views.',
    region: 'prelitoral',
    comarca: 'Bages',
    difficulty: 'moderate',
    distanceKm: 16,
    elevationGainM: 920,
    durationHours: 6,
    center: { lat: 41.593, lon: 1.838 },
    tags: ['limestone', 'cultural', 'summit'],
    infoUrl: 'https://www.montserratvisita.com/en',
  },
  {
    id: 'hike-pedraforca',
    slug: 'pedraforca-classic',
    name: 'Pedraforca — Enforcadura & Pollegó Superior',
    summary:
      'Catalunya’s most iconic peak profile: short, steep, and exposed in places — not for bad weather days.',
    region: 'prelitoral',
    comarca: 'Berguedà',
    difficulty: 'hard',
    distanceKm: 11,
    elevationGainM: 780,
    durationHours: 6,
    center: { lat: 42.239, lon: 1.705 },
    tags: ['summit', 'scramble', 'iconic'],
    infoUrl: 'https://parcsnaturals.gencat.cat/ca/agenda/espai/pedraforca',
  },
  {
    id: 'hike-aiguestortes-sant-maurici',
    slug: 'aiguestortes-estany-sant-maurici',
    name: 'Aigüestortes — Estany de Sant Maurici',
    summary:
      'Glacial lakes and granite walls beneath the Encantats — day-hike friendly with shuttle access in season.',
    region: 'pirineu',
    comarca: 'Pallars Sobirà',
    difficulty: 'moderate',
    distanceKm: 8,
    elevationGainM: 320,
    durationHours: 4,
    center: { lat: 42.583, lon: 1.0 },
    tags: ['lakes', 'national-park', 'wildlife'],
    infoUrl: 'https://parcsnaturals.gencat.cat/ca/agenda/espai/aiguestortes',
  },
  {
    id: 'hike-carros-de-foc',
    slug: 'carros-de-foc',
    name: 'Carros de Foc (circuit)',
    summary:
      'Hut-to-hut high route through Aigüestortes — serious logistics, weather windows, and booking in peak season.',
    region: 'pirineu',
    comarca: 'Pallars Sobirà',
    difficulty: 'expert',
    distanceKm: 55,
    elevationGainM: 9200,
    durationHours: 48,
    center: { lat: 42.55, lon: 0.98 },
    tags: ['multi-day', 'refugi', 'alpine'],
    infoUrl: 'https://parcsnaturals.gencat.cat/ca/agenda/espai/aiguestortes',
  },
  {
    id: 'hike-montseny-turo-home',
    slug: 'montseny-turo-de-lhome',
    name: 'Montseny — Matagalls & Turó de l’Home',
    summary:
      'Mediterranean maquis climbing into beech forest and the highest peaks south of the Pyrenees proper.',
    region: 'prelitoral',
    comarca: 'Vallès Oriental',
    difficulty: 'moderate',
    distanceKm: 14,
    elevationGainM: 850,
    durationHours: 5.5,
    center: { lat: 41.776, lon: 2.432 },
    tags: ['forest', 'summit', 'unesco-biosphere'],
    infoUrl: 'https://parcsnaturals.gencat.cat/ca/agenda/espai/montseny',
  },
  {
    id: 'hike-gr92-garraf',
    slug: 'gr92-garraf-sitges',
    name: 'GR 92 — Garraf cliffs toward Sitges',
    summary:
      'Limestone coast, vineyards, and Mediterranean blues — pick a stage that matches heat and water carries.',
    region: 'costa',
    comarca: 'Garraf',
    difficulty: 'moderate',
    distanceKm: 18,
    elevationGainM: 520,
    durationHours: 5,
    center: { lat: 41.245, lon: 1.865 },
    tags: ['coastal', 'long-distance', 'sea'],
    infoUrl: 'https://www.caminsdelparc.cat/',
  },
  {
    id: 'hike-cami-ronda',
    slug: 'cami-de-ronda-sant-feliu',
    name: 'Camí de Ronda — Sant Feliu to S’Agaró',
    summary:
      'Classic Costa Brava tread: pine-scented coves, low cliffs, and swimming options in calm weather.',
    region: 'costa',
    comarca: 'Baix Empordà',
    difficulty: 'easy',
    distanceKm: 10,
    elevationGainM: 280,
    durationHours: 3,
    center: { lat: 41.784, lon: 3.03 },
    tags: ['coastal', 'swim-stop', 'family-friendly'],
    infoUrl: 'https://www.costabrava.org/',
  },
  {
    id: 'hike-cap-de-creus',
    slug: 'cap-de-creus-cadaques',
    name: 'Cap de Creus — Far & slate sculptures',
    summary:
      'Tramuntana-sculpted schist, lighthouses, and surreal rock forms at the eastern tip of the peninsula.',
    region: 'costa',
    comarca: 'Alt Empordà',
    difficulty: 'moderate',
    distanceKm: 13,
    elevationGainM: 450,
    durationHours: 4.5,
    center: { lat: 42.315, lon: 3.276 },
    tags: ['coastal', 'wind', 'geology'],
    infoUrl: 'https://parcsnaturals.gencat.cat/ca/agenda/espai/cap-de-creus',
  },
  {
    id: 'hike-vall-de-boi',
    slug: 'vall-de-boi-sant-quirc',
    name: 'Vall de Boí — Sant Quirc & Romanesque views',
    summary:
      'World-heritage churches plus high pastures — combine short peaks with cultural stops in the valley.',
    region: 'pirineu',
    comarca: 'Alta Ribagorça',
    difficulty: 'moderate',
    distanceKm: 9,
    elevationGainM: 480,
    durationHours: 4,
    center: { lat: 42.507, lon: 0.848 },
    tags: ['culture', 'village', 'mountain'],
    infoUrl: 'https://www.vallboi.cat/',
  },
  {
    id: 'hike-gr107-bons-hommes',
    slug: 'cami-dels-bons-hommes-stage',
    name: 'Camí dels Bons Homes (GR 107) — Cerdanya stage',
    summary:
      'Cathar escape route history crossing cols and pastures — tackle as a day slice or a longer traverse.',
    region: 'interior',
    comarca: 'Cerdanya / Alt Urgell',
    difficulty: 'moderate',
    distanceKm: 22,
    elevationGainM: 900,
    durationHours: 7,
    center: { lat: 42.35, lon: 1.72 },
    tags: ['historic-trail', 'borderlands', 'long-distance'],
    infoUrl: 'https://www.caminsdelparc.cat/',
  },
  {
    id: 'hike-taga',
    slug: 'taga-des-de-ripoll',
    name: 'Taga — Ripollès summit',
    summary:
      'Straightforward summit day with big Pyrenean feel and fewer crowds than the big massifs to the west.',
    region: 'pirineu',
    comarca: 'Ripollès',
    difficulty: 'moderate',
    distanceKm: 10,
    elevationGainM: 720,
    durationHours: 4.5,
    center: { lat: 42.295, lon: 2.175 },
    tags: ['summit', 'grass-ridge', 'views'],
    infoUrl: 'https://parcsnaturals.gencat.cat/',
  },
  {
    id: 'hike-puigsacalm',
    slug: 'puigsacalm-osona',
    name: 'Puigsacalm — Osona twin tops',
    summary:
      'Short, steep pulls to two rounded summits — a regional favourite for sunrise and winter clarity.',
    region: 'interior',
    comarca: 'Osona',
    difficulty: 'moderate',
    distanceKm: 11,
    elevationGainM: 820,
    durationHours: 5,
    center: { lat: 42.127, lon: 2.408 },
    tags: ['summit', 'short-steep', 'panorama'],
    infoUrl: 'https://parcsnaturals.gencat.cat/',
  },
  {
    id: 'hike-montserrat-santa-cova',
    slug: 'montserrat-santa-cova',
    name: 'Montserrat — Monestir to Santa Cova',
    summary:
      'Paved pilgrims’ path and steps to the cave chapel beneath the serrated ridge — a manageable half-day add-on to the monastery visit.',
    region: 'prelitoral',
    comarca: 'Bages',
    difficulty: 'easy',
    distanceKm: 5,
    elevationGainM: 220,
    durationHours: 2,
    center: { lat: 41.592, lon: 1.835 },
    tags: ['pilgrimage', 'monastery', 'family-friendly'],
    infoUrl: 'https://www.montserratvisita.com/en',
  },
  {
    id: 'hike-parc-garraf-pla-la-cruz',
    slug: 'parc-del-garraf-pla-la-cruz',
    name: 'Parc del Garraf — Pla de la Querola & la Cruz',
    summary:
      'Open limestone hills and vineyard edges between the coast and Penedès — sea breezes, short steep pulls, and big sky.',
    region: 'costa',
    comarca: 'Garraf',
    difficulty: 'moderate',
    distanceKm: 11,
    elevationGainM: 400,
    durationHours: 3.5,
    center: { lat: 41.305, lon: 1.885 },
    tags: ['vineyards', 'limestone', 'sea-views'],
    infoUrl: 'https://parcsnaturals.gencat.cat/',
  },
];
