/**
 * Remove auto-import rows that duplicate hand-curated places (from duplicate report).
 * Usage: npx tsx scripts/prune-curated-duplicates.ts
 */

import { readFile, readdir, rename, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

import type { Place } from '../app/lib/directory/types';
import { PROJECT_ROOT } from './lib/project-env';

const AUTO_FILE = path.join(PROJECT_ROOT, 'app', 'lib', 'directory', 'auto-import.places.json');
const REPORT = path.join(PROJECT_ROOT, 'reports', 'place-duplicates-report.json');
const GOOGLE_DIR = path.join(PROJECT_ROOT, 'public', 'images', 'venues', 'google');
const GEN_IMAGES = path.join(PROJECT_ROOT, 'app', 'lib', 'directory', 'venueGoogleImages.generated.ts');
const GEN_ATTRS = path.join(PROJECT_ROOT, 'app', 'lib', 'directory', 'venueGoogleAttributions.generated.ts');

/** Auto slugs to drop (name-match pairs only; excludes proximity false positives). */
const PRUNE_AUTO_SLUGS = [
  'adn-galeria-1',
  'ngels-barcelona',
  'lauditori',
  'big-bang-bar-1',
  'd-origen-coffee-roasters-1',
  'el-molino-1',
  'escat-gallery-1',
  'ethall-1',
  'fab-lab-barcelona-1',
  'galeria-joan-gaspar-1',
  'harlem-jazz-club-1',
  'heliog-bal',
  'jamboree',
  'load-gallery-1',
  'moco-museum-barcelona-1',
  'morrow-coffee-1',
  'onis-coffee-1',
  'roast-club-caf',
  'sala-apolo-1',
  'slow-barcelona-1',
  'slowmov',
  'soda-ac-stic',
  'transfolab-bcn-1',
] as const;

const pruneSet = new Set<string>(PRUNE_AUTO_SLUGS);

async function writeImageGen(map: Record<string, string>) {
  const keys = Object.keys(map).sort();
  const lines = keys.map((k) => `  '${k}': '${map[k]}',`);
  const body = `/**
 * Google Places photos saved under /images/venues/google/*
 * Auto-generated by scripts/fetch-venue-google-photos.ts — do not edit by hand.
 * Re-run: npm run fetch:venue-google-photos
 */
export const VENUE_GOOGLE_IMAGE_BY_SLUG: Partial<Record<string, string>> = {
${lines.join('\n')}
};
`;
  await writeFile(GEN_IMAGES, body, 'utf8');
}

async function writeAttrGen(map: Record<string, { displayName: string; uri?: string }[]>) {
  const keys = Object.keys(map).sort();
  const lines = keys.map((k) => `  '${k}': ${JSON.stringify(map[k])},`);
  const body = `/**
 * Required attributions when non-empty (Google Places photo policy).
 * Auto-generated by scripts/fetch-venue-google-photos.ts — do not edit by hand.
 */
export type GooglePhotoAttribution = { displayName: string; uri?: string };

export const VENUE_GOOGLE_ATTRIBUTIONS: Partial<
  Record<string, GooglePhotoAttribution[]>
> = {
${lines.join('\n')}
};
`;
  await writeFile(GEN_ATTRS, body, 'utf8');
}

async function main() {
  const raw = await readFile(AUTO_FILE, 'utf8');
  const auto = JSON.parse(raw) as Place[];
  const before = auto.length;
  const kept = auto.filter((p) => !pruneSet.has(p.slug));
  const removed = before - kept.length;

  if (removed !== PRUNE_AUTO_SLUGS.length) {
    const missing = PRUNE_AUTO_SLUGS.filter(
      (s) => !auto.some((p) => p.slug === s),
    );
    const extra = kept.filter((p) => pruneSet.has(p.slug));
    if (missing.length) console.warn(`[warn] not in auto-import: ${missing.join(', ')}`);
    if (extra.length) console.warn(`[warn] still present: ${extra.map((p) => p.slug).join(', ')}`);
  }

  const tmp = `${AUTO_FILE}.${process.pid}.tmp`;
  await writeFile(tmp, `${JSON.stringify(kept, null, 2)}\n`, 'utf8');
  await rename(tmp, AUTO_FILE);

  let filesDeleted = 0;
  for (const slug of pruneSet) {
    for (const ext of ['jpg', 'jpeg', 'png', 'webp']) {
      const f = path.join(GOOGLE_DIR, `${slug}.${ext}`);
      try {
        await rm(f, { force: true });
        filesDeleted++;
      } catch {
        /* ignore */
      }
    }
  }

  const { SEED_PLACES } = await import('../app/lib/directory/seed.server');
  const validSlugs = new Set(SEED_PLACES.map((p) => p.slug));

  const imageMap: Record<string, string> = {};
  for (const ent of await readdir(GOOGLE_DIR, { withFileTypes: true }).catch(() => [])) {
    if (!ent.isFile() || !ent.name.includes('.')) continue;
    const slugPart = ent.name.replace(/\.[^.]+$/, '');
    if (!validSlugs.has(slugPart)) continue;
    imageMap[slugPart] = `/images/venues/google/${ent.name}`;
  }

  const { VENUE_GOOGLE_ATTRIBUTIONS } = await import(
    '../app/lib/directory/venueGoogleAttributions.generated.ts'
  );
  const attrFiltered: Record<string, { displayName: string; uri?: string }[]> = {};
  for (const [k, v] of Object.entries(VENUE_GOOGLE_ATTRIBUTIONS)) {
    if (validSlugs.has(k) && v?.length) attrFiltered[k] = v;
  }

  await writeImageGen(imageMap);
  await writeAttrGen(attrFiltered);

  const summary = {
    prunedAt: new Date().toISOString(),
    prunedAutoSlugs: [...PRUNE_AUTO_SLUGS],
    autoImportBefore: before,
    autoImportAfter: kept.length,
    removed,
    totalPlacesAfter: SEED_PLACES.length,
    googleFilesDeleted: filesDeleted,
    googleImageEntries: Object.keys(imageMap).length,
    attributionEntries: Object.keys(attrFiltered).length,
  };

  await writeFile(
    path.join(PROJECT_ROOT, 'reports', 'place-duplicates-prune-last-run.json'),
    `${JSON.stringify(summary, null, 2)}\n`,
    'utf8',
  );

  console.log(`Removed ${removed} auto-import rows (${before} → ${kept.length})`);
  console.log(`Total SEED_PLACES now: ${SEED_PLACES.length}`);
  console.log(`Google image map entries: ${Object.keys(imageMap).length}`);
  console.log(`Deleted google files (attempts): ${filesDeleted}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
